title:              JooYoung's Blog
email:              2007kjy@naver.com
description:        This is my private blog.
author:             Start Bootstrap
url:                "https://jooyoungkim97.github.io"

# Social Profiles
twitter_username:   
github_username:    jooyoung97
facebook_username:  김주영
instagram_username: zzoo00__
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
